version: "3"
services:
  node:
    image: ${PROJECT_NAME}/node:latest
    container_name: ${PROJECT_NAME}_node
    build:
      context: .
      dockerfile: ./node/Dockerfile
    volumes:
      - ./node:/node
    expose:
      - ${NODE_PORT}
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    expose:
      - ${MYSQL_PORT}

  nginx:
    image: ${PROJECT_NAME}/nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: ./nginx
      args:
        domain: ${DOMAIN}
        response: proxy_pass http://node:${NODE_PORT}
    volumes:
      - ./certbot/letsencrypt/:/data/letsencrypt
      - ./certbot/certs:/data/certs
    ports:
      - 80:80
      - 443:443
    restart: always

  certbot:
    image: ${PROJECT_NAME}/certbot:latest
    container_name: ${PROJECT_NAME}_certbot
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    volumes:
      - ./certbot/letsencrypt:/data/letsencrypt
      - ./certbot/certs:/data/certs
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      ENVIRONMENT: ${ENVIRONMENT}
    tty: true
