version: "3"
services:
  # node:
  #   image: ${PROJECT_NAME}/node:latest
  #   build:
  #     context: .
  #     dockerfile: ./node/Dockerfile
  #   volumes:
  #     - ./node:/node
  #   # ports:
  #   #   - ${PORT}:${PORT}
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_HOST: mysql # target container name
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   restart: always
  #   expose:
  #     - ${NODE_PORT}

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   # ports:
  #   #   - ${MYSQL_PORT}:${MYSQL_PORT}
  #   restart: always
  #   expose:
  #     - ${MYSQL_PORT}

  nginx:
    image: ${PROJECT_NAME}/nginx:latest
    build:
      context: ./nginx
      args:
        domain: ${DOMAIN}
    volumes:
      - ./www:/data/www
      - ./certbot/letsencrypt/:/data/letsencrypt
      - ./certbot/certs:/data/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certbot
    # - node
    restart: always

  certbot:
    image: ${PROJECT_NAME}/certbot:latest
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    volumes:
      - ./certbot/letsencrypt:/data/letsencrypt
      - ./certbot/certs:/data/certs
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    tty: true
