version: "3"
services:
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    volumes:
      - ./node:/node
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql # target container name
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx
      - ./www:/data/www
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node
    restart: always
