FROM certbot/certbot
# FROM ubuntu

# COPY scripts /root/scripts/

# RUN apt-get update
# RUN apt-get install -y letsencrypt

# ENTRYPOINT bash -c "bash /root/scripts/run-certbot.sh && sleep infinity"

# RUN apt-get update \
# 	&& apt-get install software-properties-common -y \
# 	&& add-apt-repository ppa:certbot/certbot \
# 	&& apt-get update \
# 	&& apt-get install python-certbot-nginx

CMD tail -F anything
